apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp21
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: san21doc/simpleapp
        ports:
        - containerPort: 80
